/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsHomeArchitectRouteImport } from './routes/settings/home-architect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHomeArchitectRoute = SettingsHomeArchitectRouteImport.update({
  id: '/settings/home-architect',
  path: '/settings/home-architect',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings/home-architect': typeof SettingsHomeArchitectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/home-architect': typeof SettingsHomeArchitectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings/home-architect': typeof SettingsHomeArchitectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings/home-architect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings/home-architect'
  id: '__root__' | '/' | '/settings/home-architect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsHomeArchitectRoute: typeof SettingsHomeArchitectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/home-architect': {
      id: '/settings/home-architect'
      path: '/settings/home-architect'
      fullPath: '/settings/home-architect'
      preLoaderRoute: typeof SettingsHomeArchitectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsHomeArchitectRoute: SettingsHomeArchitectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
