/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LightingRouteRouteImport } from './routes/lighting/route'
import { Route as LightingIndexRouteImport } from './routes/lighting/index'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as SettingsHomeArchitectRouteRouteImport } from './routes/settings/home-architect/route'
import { Route as SettingsHomeArchitectIndexRouteImport } from './routes/settings/home-architect/index'
import { Route as ApiLightingEventsRouteImport } from './routes/api/lighting/events'

const LightingRouteRoute = LightingRouteRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingIndexRoute = LightingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LightingRouteRoute,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHomeArchitectRouteRoute =
  SettingsHomeArchitectRouteRouteImport.update({
    id: '/settings/home-architect',
    path: '/settings/home-architect',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsHomeArchitectIndexRoute =
  SettingsHomeArchitectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsHomeArchitectRouteRoute,
  } as any)
const ApiLightingEventsRoute = ApiLightingEventsRouteImport.update({
  id: '/api/lighting/events',
  path: '/api/lighting/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/lighting': typeof LightingRouteRouteWithChildren
  '/settings/home-architect': typeof SettingsHomeArchitectRouteRouteWithChildren
  '/': typeof dashboardIndexRoute
  '/lighting/': typeof LightingIndexRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
  '/settings/home-architect/': typeof SettingsHomeArchitectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/lighting': typeof LightingIndexRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
  '/settings/home-architect': typeof SettingsHomeArchitectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/lighting': typeof LightingRouteRouteWithChildren
  '/settings/home-architect': typeof SettingsHomeArchitectRouteRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/lighting/': typeof LightingIndexRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
  '/settings/home-architect/': typeof SettingsHomeArchitectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/lighting'
    | '/settings/home-architect'
    | '/'
    | '/lighting/'
    | '/api/lighting/events'
    | '/settings/home-architect/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lighting' | '/api/lighting/events' | '/settings/home-architect'
  id:
    | '__root__'
    | '/lighting'
    | '/settings/home-architect'
    | '/(dashboard)/'
    | '/lighting/'
    | '/api/lighting/events'
    | '/settings/home-architect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LightingRouteRoute: typeof LightingRouteRouteWithChildren
  SettingsHomeArchitectRouteRoute: typeof SettingsHomeArchitectRouteRouteWithChildren
  dashboardIndexRoute: typeof dashboardIndexRoute
  ApiLightingEventsRoute: typeof ApiLightingEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting/': {
      id: '/lighting/'
      path: '/'
      fullPath: '/lighting/'
      preLoaderRoute: typeof LightingIndexRouteImport
      parentRoute: typeof LightingRouteRoute
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/home-architect': {
      id: '/settings/home-architect'
      path: '/settings/home-architect'
      fullPath: '/settings/home-architect'
      preLoaderRoute: typeof SettingsHomeArchitectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/home-architect/': {
      id: '/settings/home-architect/'
      path: '/'
      fullPath: '/settings/home-architect/'
      preLoaderRoute: typeof SettingsHomeArchitectIndexRouteImport
      parentRoute: typeof SettingsHomeArchitectRouteRoute
    }
    '/api/lighting/events': {
      id: '/api/lighting/events'
      path: '/api/lighting/events'
      fullPath: '/api/lighting/events'
      preLoaderRoute: typeof ApiLightingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LightingRouteRouteChildren {
  LightingIndexRoute: typeof LightingIndexRoute
}

const LightingRouteRouteChildren: LightingRouteRouteChildren = {
  LightingIndexRoute: LightingIndexRoute,
}

const LightingRouteRouteWithChildren = LightingRouteRoute._addFileChildren(
  LightingRouteRouteChildren,
)

interface SettingsHomeArchitectRouteRouteChildren {
  SettingsHomeArchitectIndexRoute: typeof SettingsHomeArchitectIndexRoute
}

const SettingsHomeArchitectRouteRouteChildren: SettingsHomeArchitectRouteRouteChildren =
  {
    SettingsHomeArchitectIndexRoute: SettingsHomeArchitectIndexRoute,
  }

const SettingsHomeArchitectRouteRouteWithChildren =
  SettingsHomeArchitectRouteRoute._addFileChildren(
    SettingsHomeArchitectRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  LightingRouteRoute: LightingRouteRouteWithChildren,
  SettingsHomeArchitectRouteRoute: SettingsHomeArchitectRouteRouteWithChildren,
  dashboardIndexRoute: dashboardIndexRoute,
  ApiLightingEventsRoute: ApiLightingEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
