/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as HomeArchitectIndexRouteImport } from './routes/home-architect/index'
import { Route as HomeAssistantObserverIndexRouteImport } from './routes/home-assistant-observer/index'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ApiCarEventsRouteImport } from './routes/api/car.events'
import { Route as ApiEnvironmentEventsRouteImport } from './routes/api/environment/events'
import { Route as ApiLightingEventsRouteImport } from './routes/api/lighting/events'

const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeArchitectIndexRoute = HomeArchitectIndexRouteImport.update({
  id: '/home-architect/',
  path: '/home-architect/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeAssistantObserverIndexRoute =
  HomeAssistantObserverIndexRouteImport.update({
    id: '/home-assistant-observer/',
    path: '/home-assistant-observer/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCarEventsRoute = ApiCarEventsRouteImport.update({
  id: '/api/car/events',
  path: '/api/car/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnvironmentEventsRoute = ApiEnvironmentEventsRouteImport.update({
  id: '/api/environment/events',
  path: '/api/environment/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLightingEventsRoute = ApiLightingEventsRouteImport.update({
  id: '/api/lighting/events',
  path: '/api/lighting/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/events': typeof ApiEventsRoute
  '/': typeof dashboardIndexRoute
  '/home-architect/': typeof HomeArchitectIndexRoute
  '/home-assistant-observer/': typeof HomeAssistantObserverIndexRoute
  '/map/': typeof MapIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/car/events': typeof ApiCarEventsRoute
  '/api/environment/events': typeof ApiEnvironmentEventsRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
}
export interface FileRoutesByTo {
  '/api/events': typeof ApiEventsRoute
  '/': typeof dashboardIndexRoute
  '/home-architect': typeof HomeArchitectIndexRoute
  '/home-assistant-observer': typeof HomeAssistantObserverIndexRoute
  '/map': typeof MapIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/car/events': typeof ApiCarEventsRoute
  '/api/environment/events': typeof ApiEnvironmentEventsRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/events': typeof ApiEventsRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/home-architect/': typeof HomeArchitectIndexRoute
  '/home-assistant-observer/': typeof HomeAssistantObserverIndexRoute
  '/map/': typeof MapIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/car/events': typeof ApiCarEventsRoute
  '/api/environment/events': typeof ApiEnvironmentEventsRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api/events'
    | '/'
    | '/home-architect/'
    | '/home-assistant-observer/'
    | '/map/'
    | '/settings/'
    | '/api/car/events'
    | '/api/environment/events'
    | '/api/lighting/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/events'
    | '/'
    | '/home-architect'
    | '/home-assistant-observer'
    | '/map'
    | '/settings'
    | '/api/car/events'
    | '/api/environment/events'
    | '/api/lighting/events'
  id:
    | '__root__'
    | '/api/events'
    | '/(dashboard)/'
    | '/home-architect/'
    | '/home-assistant-observer/'
    | '/map/'
    | '/settings/'
    | '/api/car/events'
    | '/api/environment/events'
    | '/api/lighting/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiEventsRoute: typeof ApiEventsRoute
  dashboardIndexRoute: typeof dashboardIndexRoute
  HomeArchitectIndexRoute: typeof HomeArchitectIndexRoute
  HomeAssistantObserverIndexRoute: typeof HomeAssistantObserverIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiCarEventsRoute: typeof ApiCarEventsRoute
  ApiEnvironmentEventsRoute: typeof ApiEnvironmentEventsRoute
  ApiLightingEventsRoute: typeof ApiLightingEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-architect/': {
      id: '/home-architect/'
      path: '/home-architect'
      fullPath: '/home-architect/'
      preLoaderRoute: typeof HomeArchitectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-assistant-observer/': {
      id: '/home-assistant-observer/'
      path: '/home-assistant-observer'
      fullPath: '/home-assistant-observer/'
      preLoaderRoute: typeof HomeAssistantObserverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/car/events': {
      id: '/api/car/events'
      path: '/api/car/events'
      fullPath: '/api/car/events'
      preLoaderRoute: typeof ApiCarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/environment/events': {
      id: '/api/environment/events'
      path: '/api/environment/events'
      fullPath: '/api/environment/events'
      preLoaderRoute: typeof ApiEnvironmentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lighting/events': {
      id: '/api/lighting/events'
      path: '/api/lighting/events'
      fullPath: '/api/lighting/events'
      preLoaderRoute: typeof ApiLightingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiEventsRoute: ApiEventsRoute,
  dashboardIndexRoute: dashboardIndexRoute,
  HomeArchitectIndexRoute: HomeArchitectIndexRoute,
  HomeAssistantObserverIndexRoute: HomeAssistantObserverIndexRoute,
  MapIndexRoute: MapIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiCarEventsRoute: ApiCarEventsRoute,
  ApiEnvironmentEventsRoute: ApiEnvironmentEventsRoute,
  ApiLightingEventsRoute: ApiLightingEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
