/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapIndexRouteImport } from './routes/map/index'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as SettingsHomeArchitectRouteRouteImport } from './routes/settings/home-architect/route'
import { Route as SettingsHomeArchitectIndexRouteImport } from './routes/settings/home-architect/index'
import { Route as ApiLightingEventsRouteImport } from './routes/api/lighting/events'
import { Route as ApiEnvironmentEventsRouteImport } from './routes/api/environment/events'

const MapIndexRoute = MapIndexRouteImport.update({
  id: '/map/',
  path: '/map/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsHomeArchitectRouteRoute =
  SettingsHomeArchitectRouteRouteImport.update({
    id: '/settings/home-architect',
    path: '/settings/home-architect',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsHomeArchitectIndexRoute =
  SettingsHomeArchitectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsHomeArchitectRouteRoute,
  } as any)
const ApiLightingEventsRoute = ApiLightingEventsRouteImport.update({
  id: '/api/lighting/events',
  path: '/api/lighting/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnvironmentEventsRoute = ApiEnvironmentEventsRouteImport.update({
  id: '/api/environment/events',
  path: '/api/environment/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings/home-architect': typeof SettingsHomeArchitectRouteRouteWithChildren
  '/': typeof dashboardIndexRoute
  '/map/': typeof MapIndexRoute
  '/api/environment/events': typeof ApiEnvironmentEventsRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
  '/settings/home-architect/': typeof SettingsHomeArchitectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof dashboardIndexRoute
  '/map': typeof MapIndexRoute
  '/api/environment/events': typeof ApiEnvironmentEventsRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
  '/settings/home-architect': typeof SettingsHomeArchitectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/settings/home-architect': typeof SettingsHomeArchitectRouteRouteWithChildren
  '/(dashboard)/': typeof dashboardIndexRoute
  '/map/': typeof MapIndexRoute
  '/api/environment/events': typeof ApiEnvironmentEventsRoute
  '/api/lighting/events': typeof ApiLightingEventsRoute
  '/settings/home-architect/': typeof SettingsHomeArchitectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings/home-architect'
    | '/'
    | '/map/'
    | '/api/environment/events'
    | '/api/lighting/events'
    | '/settings/home-architect/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/api/environment/events'
    | '/api/lighting/events'
    | '/settings/home-architect'
  id:
    | '__root__'
    | '/settings/home-architect'
    | '/(dashboard)/'
    | '/map/'
    | '/api/environment/events'
    | '/api/lighting/events'
    | '/settings/home-architect/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsHomeArchitectRouteRoute: typeof SettingsHomeArchitectRouteRouteWithChildren
  dashboardIndexRoute: typeof dashboardIndexRoute
  MapIndexRoute: typeof MapIndexRoute
  ApiEnvironmentEventsRoute: typeof ApiEnvironmentEventsRoute
  ApiLightingEventsRoute: typeof ApiLightingEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map/': {
      id: '/map/'
      path: '/map'
      fullPath: '/map/'
      preLoaderRoute: typeof MapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/home-architect': {
      id: '/settings/home-architect'
      path: '/settings/home-architect'
      fullPath: '/settings/home-architect'
      preLoaderRoute: typeof SettingsHomeArchitectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/home-architect/': {
      id: '/settings/home-architect/'
      path: '/'
      fullPath: '/settings/home-architect/'
      preLoaderRoute: typeof SettingsHomeArchitectIndexRouteImport
      parentRoute: typeof SettingsHomeArchitectRouteRoute
    }
    '/api/lighting/events': {
      id: '/api/lighting/events'
      path: '/api/lighting/events'
      fullPath: '/api/lighting/events'
      preLoaderRoute: typeof ApiLightingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/environment/events': {
      id: '/api/environment/events'
      path: '/api/environment/events'
      fullPath: '/api/environment/events'
      preLoaderRoute: typeof ApiEnvironmentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsHomeArchitectRouteRouteChildren {
  SettingsHomeArchitectIndexRoute: typeof SettingsHomeArchitectIndexRoute
}

const SettingsHomeArchitectRouteRouteChildren: SettingsHomeArchitectRouteRouteChildren =
  {
    SettingsHomeArchitectIndexRoute: SettingsHomeArchitectIndexRoute,
  }

const SettingsHomeArchitectRouteRouteWithChildren =
  SettingsHomeArchitectRouteRoute._addFileChildren(
    SettingsHomeArchitectRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  SettingsHomeArchitectRouteRoute: SettingsHomeArchitectRouteRouteWithChildren,
  dashboardIndexRoute: dashboardIndexRoute,
  MapIndexRoute: MapIndexRoute,
  ApiEnvironmentEventsRoute: ApiEnvironmentEventsRoute,
  ApiLightingEventsRoute: ApiLightingEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
